// Enrichissements des histoires des prophètes (fusionnés à l'affichage)
window.PROPHETE_EXTRA = {
  'Adam': `<br><br><strong>📖 Enseignements d'Adam :</strong> Adam enseigna à ses enfants comment se repentir auprès d'Allah. Il leur transmit les rites du pèlerinage et les fondements de la foi monothéiste. Selon Ibn Kathir, Adam vécut mille ans après sa descente sur Terre et fut enterré en Arabie.
<br><br><strong>📖 Sa place dans l'islam :</strong> Les musulmans croient qu'Adam fut le premier prophète et que tous les humains descendent de lui. Son histoire rappelle que l'homme fut créé pour adorer Allah et que la connaissance est un don divin.`,
  'Idris': `<br><br><strong>📖 Sciences et astronomie :</strong> Les savants mentionnent qu'Idris fut le premier à utiliser l'écriture, à coudre des vêtements et à observer les mouvements des astres pour le bien des hommes, sans tomber dans l'astrologie interdite.
<br><br><strong>📖 Son rang élevé :</strong> Allah dit dans le Coran qu'Il l'éleva à un rang très haut. Certains exégètes comprennent qu'il fut élevé au quatrième ciel de son vivant, ce qui témoigne de sa proximité avec son Seigneur.`,
  'Noé (Nuh)': `<br><br><strong>📖 Les trois fils de Noé :</strong> Après le déluge, les fils de Noé — Sam, Ham et Yafith — dispersèrent leurs descendants sur la Terre. De leur descendance proviennent les différents peuples de l'humanité.
<br><br><strong>📖 Patience exemplaire :</strong> Noé appela son peuple jour et nuit, en secret et en public, pendant 950 ans. Malgré les moqueries et les menaces, il ne cessa jamais de transmettre le message d'Allah.`,
  'Houd': `<br><br><strong>📖 Civilisation d'Ad :</strong> Le peuple d'Ad construisait des palais majestueux à Iram, la cité aux colonnes, mentionnée dans le Coran. Leur architecture était remarquable mais leur orgueil les aveugla.
<br><br><strong>📖 Le vent destructeur :</strong> Allah envoya contre eux un vent glacial et violent qui les arracha de leurs demeures et les projeta sur le sol, morts comme des troncs de palmiers déracinés.`,
  'Salih': `<br><br><strong>📖 Al-Hijr :</strong> Les demeures taillées dans les rochers du peuple de Thamud existent encore en Arabie saoudite (Madain Salih). Elles témoignent de leur puissance et servent de rappel aux visiteurs.
<br><br><strong>📖 Le conseil de Salih :</strong> Salih leur rappela constamment les bienfaits d'Allah : il les fit succéder au peuple d'Ad, leur donna des jardins, des sources et des montagnes qu'ils taillaient en maisons.`,
  'Abraham (Ibrahim)': `<br><br><strong>📖 L'hospitalité d'Abraham :</strong> Abraham était réputé pour son hospitalité. Il accueillit les anges sous forme d'hommes et prépara un veau pour eux, ignorant qu'ils étaient des messagers d'Allah venant annoncer la naissance d'Isaac.
<br><br><strong>📖 La Mecque et Zamzam :</strong> Lorsqu'Hajar et Ismaël furent laissés en Arabie, l'eau de Zamzam jaillit par la miséricorde d'Allah. Abraham revisita son fils et ensemble ils reconstruisirent la Kaaba sur les fondations d'Adam.`,
  'Lot (Lut)': `<br><br><strong>📖 L'hospitalité de Lot :</strong> Lot accueillit les étrangers en dépit des mœurs de son peuple. Les habitants de Sodome interdisaient aux voyageurs de passer, volant leurs biens et commettant des abominations.
<br><br><strong>📖 Le départ en catastrophe :</strong> Les anges ordonnèrent à Lot de partir avec sa famille la nuit, sans se retourner. Sa femme désobéit, regarda en arrière et fut frappée comme les autres.`,
  'Ismaël (Ismail)': `<br><br><strong>📖 La fondation de La Mecque :</strong> Ismaël grandit en Arabie et apprit l'arabe. Avec Abraham, il établit les rites du Hajj : le Tawaf, le Sa'y entre Safa et Marwa, et l'offrande d'un sacrifice.
<br><br><strong>📖 Ancêtre du Prophète Muhammad :</strong> Ismaël est l'ancêtre direct des tribus arabes, dont Quraysh, la tribu du Prophète Muhammad (paix et bénédictions sur lui).`,
  'Isaac (Ishaq)': `<br><br><strong>📖 La lignée bénie :</strong> De la descendance d'Isaac sortirent de nombreux prophètes : Jacob, Joseph, Moïse, Aaron, David, Salomon, Zacharie, Jean-Baptiste et Jésus (paix sur eux tous).
<br><br><strong>📖 Foi et confiance :</strong> Abraham et Sarah eurent confiance en la promesse d'Allah malgré leur grand âge, montrant que rien n'est impossible pour le Créateur.`,
  'Jacob (Ya\'qub)': `<br><br><strong>📖 Le surnom d'Israël :</strong> Jacob fut aussi appelé Israël, signifiant « serviteur d'Allah ». Ses douze fils devinrent les patriarches des douze tribus d'Israël.
<br><br><strong>📖 La perte de Joseph :</strong> Jacob pleura si longtemps pour Joseph qu'il perdit la vue. Pourtant, il ne perdit jamais confiance et disait : « Je me plains à Allah de mon chagrin. »`,
  'Joseph (Yusuf)': `<br><br><strong>📖 La sourate Yusuf :</strong> Le Coran consacre une sourate entière à l'histoire de Joseph, appelée « la plus belle des histoires » (Ahsan al-Qasas). Elle contient de nombreuses leçons sur la patience, la chasteté et le pardon.
<br><br><strong>📖 Gouverneur d'Égypte :</strong> Joseph géra les réserves de blé pendant sept années d'abondance pour affronter sept années de famine, sauvant l'Égypte et sa propre famille.`,
  'Job (Ayyub)': `<br><br><strong>📖 Invocation de Job :</strong> Dans sa souffrance, Job invoqua : « Le mal m'a touché, et Toi, Tu es le plus Miséricordieux des miséricordieux. » Allah exauça son appel et lui rendit sa santé, sa famille et ses biens en double.
<br><br><strong>📖 Modèle de patience (sabr) :</strong> Job est cité dans le Coran comme exemple de serviteur patient. Sa femme resta fidèle et le soutint dans l'épreuve.`,
  'Shu\'ayb': `<br><br><strong>📖 Commerce équitable :</strong> Shu'ayb interdisait toute fraude dans les balances et les mesures. Il rappelait que la richesse obtenue par l'injustice ne profite pas à l'au-delà.
<br><br><strong>📖 Lien avec Moïse :</strong> Certains exégètes mentionnent que Shu'ayb était lié à la famille de Moïse par le mariage, renforçant la continuité du message prophétique.`,
  'Moïse (Musa)': `<br><br><strong>📖 Le bâton miraculeux :</strong> Le bâton de Moïse se transforma en serpent devant Pharaon et avala les illusions des magiciens, prouvant la supériorité du miracle divin sur la sorcellerie.
<br><br><strong>📖 Kalimullah :</strong> Moïse est l'un des deux prophètes à qui Allah a parlé directement (avec Muhammad). Il reçut les Tablettes de la Torah sur le Mont Sinaï après jeûner quarante jours.
<br><br><strong>📖 Les dix plaies :</strong> Pharaon refusa de libérer les Enfants d'Israël malgré les signes : le fleuve devenu sang, les sauterelles, les grenouilles et d'autres épreuves envoyées par Allah.`,
  'Aaron (Harun)': `<br><br><strong>📖 Soutien à Moïse :</strong> Moïse demanda à Allah de confier à Aaron la mission de l'assister car il était plus éloquent. Aaron accompagna Moïse devant Pharaon et parla au peuple en son absence.
<br><br><strong>📖 Épreuve du veau d'or :</strong> Pendant l'absence de Moïse, Samiri incita le peuple à fabriquer un veau d'or. Aaron tenta de les en dissuader mais ils le menacèrent. Moïse pardonna à Aaron en comprenant la difficulté de la situation.`,
  'David (Dawud)': `<br><br><strong>📖 Les Psaumes (Zabur) :</strong> Allah révéla à David les Psaumes, un livre de louanges et d'invocations. Il récitait le Zabur avec une voix magnifique qui faisait pleurer les montagnages et les oiseaux.
<br><br><strong>📖 Justice et sagesse :</strong> David jugeait avec équité entre les disputants. Allah lui enseigna la fabrication de la cotte de mailles et lui accorda la force et la sagesse.`,
  'Salomon (Sulayman)': `<br><br><strong>📖 Royaume unique :</strong> Salomon possédait un royaume sans égal : les vents lui obéissaient, les djinns travaillaient pour lui, et il comprenait le langage des oiseaux et des fourmis.
<br><br><strong>📖 Sagesse dans le jugement :</strong> L'histoire des deux femmes disputant un enfant illustre la sagesse prodigieuse de Salomon, qui proposa de partager l'enfant pour révéler la vraie mère.`,
  'Élie (Ilyas)': `<br><br><strong>📖 Combat contre Baal :</strong> Élie défia les prêtres de l'idole Baal sur le mont Carmel. Le feu descendit du ciel sur son sacrifice, prouvant la puissance d'Allah, tandis que les prêtres de Baal furent vaincus.
<br><br><strong>📖 Persécution :</strong> Malgré les miracles, Élie fut persécuté par la reine Jézabel et dût se réfugier. Allah le nourrit et le protégea dans l'épreuve.`,
  'Élisée (Al-Yasa)': `<br><br><strong>📖 Succession d'Élie :</strong> Élisée demanda à Élie une double portion de son esprit prophétique. Il reçut ce don et continua la prédication avec des miracles : guérison des lépreux et multiplication de l'huile d'une veuve.
<br><br><strong>📖 Guidance du peuple :</strong> Élisée enseigna la loi d'Allah et rappela constamment son peuple à la droiture et à l'adoration exclusive du Créateur.`,
  'Jonas (Yunus)': `<br><br><strong>📖 Invocation dans les ténèbres :</strong> L'invocation de Jonas dans le ventre de la baleine — « La ilaha illa Anta, Subhanaka, inni kuntu minaz-zalimin » — est recommandée aux musulmans en moment de détresse.
<br><br><strong>📖 Repentir du peuple :</strong> Lorsque le peuple de Ninive vit les signes du châtiment imminent, tous se repentirent sincèrement, hommes et bêtes, et Allah leur pardonna.`,
  'Zacharie (Zakariyya)': `<br><br><strong>📖 Gardien de Marie :</strong> Zacharie prit en charge Marie (Maryam) dans le temple. Il fut témoin des miracles d'Allah envers elle : des fruits hors saison lui étaient apportés.
<br><br><strong>📖 Prière exaucée :</strong> Malgré son grand âge, Zacharie pria avec ferveur pour un enfant pieux. Allah lui donna Yahya, qui devint un prophète ascète et véridique.`,
  'Jean-Baptiste (Yahya)': `<br><br><strong>📖 Pureté et ascétisme :</strong> Yahya fut le premier à porter ce nom. Il vécut dans le détachement du monde, jeûnant le jour et priant la nuit, et ne commit aucun péché.
<br><br><strong>📖 Confirmation de Jésus :</strong> Yahya confirma la mission de Jésus (paix sur lui) et appela son peuple à la repentance et à la préparation de la venue du Messie.`,
  'Jésus (Isa)': `<br><br><strong>📖 Miracles de Jésus :</strong> Par la permission d'Allah, Jésus guérissait les lépreux, ressuscitait les morts, guérissait les aveugles de naissance et informait du contenu des maisons, comme mentionné dans le Coran.
<br><br><strong>📖 Message d'unicité :</strong> Jésus confirma la Torah et annonça un prophète à venir après lui, dont le nom est Ahmad (Muhammad). Il appela toujours à l'adoration d'Allah seul, sans associé.`,
  'Muhammad': `<br><br><strong>📖 Caractère exemplaire :</strong> Avant la prophétie, Muhammad était surnommé Al-Amin (le digne de confiance). Il était connu pour son honnêteté, sa générosité et sa droiture, même par ses ennemis.
<br><br><strong>📖 Le Coran :</strong> Le Coran fut révélé sur 23 ans, traitant de la croyance, de la législation, de l'éthique et des récits des prophètes. C'est le dernier livre révélé et il est préservé intact.
<br><br><strong>📖 Ouverture au monde :</strong> Le Prophète accueillit les délégations étrangères, envoya des lettres aux empereurs byzantin et perse, et établit des relations basées sur la justice et la paix lorsque c'était possible.
<br><br><strong>📖 Miséricorde pour l'univers :</strong> Allah dit : « Nous ne t'avons envoyé que comme miséricorde pour l'univers. » Sa Sunna (exemple) reste la référence pour tous les musulmans dans le culte, les relations sociales et la gouvernance.`
};
